Use `Using.urlInputStream` instead of `IO.toFile`
Since IO.toFile only succeeds when used directly (i.e. from sbt-precog itself).
When the resource is in a jar it fails with
java.lang.AssertionError: assertion failed: Expected protocol to be 'file' or empty in URI
jar:file:/Caches/Coursier/v1/https/maven.pkg.github.com/precog/_/com/precog/sbt-precog-core_2.12_1.0/4.0.1-e83a78e/sbt-precog-core-4.0.1-e83a78e.jar!/core/scalafmt-common.conf